package org.smicon.rest.data.mustachetemplate.controller;

import org.smicon.rest.data.mustachetemplate.controller.modelwrapper.ModelWrapperPopulator;

public interface ControllerTemplateDataI
{

	public String getControllerClassPostfix();

	public String getIdPathExtension();

	public String getIdPathExtensionOmitAutoGenerated();

	public String getCreateRouteIdPathExtension() throws Exception;

	public String getIdPathExtension(boolean aOmitAutoGeneratedIds);

	public String getIdParameters();

	public String getIdParametersOmitAutoGenerated();

	public String getCreateRouteIdParameters();

	public String getIdParameters(boolean aOmitAutoGeneratedIds);

	public String getIdSetterCode(boolean aOmitAutogeneratedIds);

	public String getSingularIdName();

	public String getIdGenerateCode() throws Exception;

	public String getIdGenerateCodeOmitAutoGenerated() throws Exception;

	public String getIdGenerateCode(boolean aOmitAutoGeneratedIds) throws Exception;

	public String getModelVariableName();

	public String getSetModelIdsOmitGeneratedCode() throws Exception;

	public String getSetModelIdsCode() throws Exception;

	public String getSetModelIdsCode(boolean aOmitAutoGeneratedIds) throws Exception;

	public String getUrlIdDelimiter();

	/*
	 * *****************************************************************************
	 * Child populators
	 * *********************************************************
	 * ********************
	 */

	public ModelWrapperPopulator getWrapperPopulator();
	
}
